book:
  path: data/origin_of_species.md 
chroma:
  db_dir: data/chromadb  
  collection_name: origin_species  

chunking:
  chunk_size: 1000  # Tamanho de cada pedaço, vou testar com 1000 primeiro
  chunk_overlap: 200  # Sobreposição pra não perder contexto

# Modelos que vou usar
models:
  embedding: sentence-transformers/all-MiniLM-L6-v2 
  llm: google/flan-t5-base